#!/usr/bin/env bash
set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

set -x

rm -rf out

clj -m cljs.main \
    -t node -O simple -co "{:verbose true}"\
    -o out/bundle.js\
    -c my.core

node out/bundle.js
